# Generated by Django 2.2.4 on 2019-09-02 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productivity_log',
            fields=[
                ('auto_increment_id', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='past_date')),
                ('details', models.TextField(blank=True, max_length=100)),
                ('hour', models.FloatField(null=True, verbose_name='productivity hour')),
            ],
        ),
    ]
